<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Confluent.Kafka.Core.Serialization.ProtobufNet</AssemblyName>
        <PackageId>Confluent.Kafka.Core.Serialization.ProtobufNet</PackageId>
        <Description>Provides serialization implementation through protobuf-net for Apache Kafka .NET client.</Description>
        <PackageTags>Apache;Kafka;Confluent;librdkafka;Serialization;protobuf-net</PackageTags>
    </PropertyGroup>

    <ItemGroup Label="Builders">
        <Compile Include="..\Shared\Builders\FunctionalBuilder``.cs"   Link="Internal\FunctionalBuilder``.cs" />
        <Compile Include="..\Shared\Builders\IFunctionalBuilder``.cs"  Link="Internal\IFunctionalBuilder``.cs" />
        <Compile Include="..\Shared\Builders\FunctionalBuilder```.cs"  Link="Internal\FunctionalBuilder```.cs" />
        <Compile Include="..\Shared\Builders\IFunctionalBuilder```.cs" Link="Internal\IFunctionalBuilder```.cs" />
    </ItemGroup>

    <ItemGroup Label="Extensions">
        <Compile Include="..\Shared\Extensions\TypeExtensions.cs" Link="Internal\TypeExtensions.cs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Confluent.Kafka.Core.Abstractions\Confluent.Kafka.Core.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="protobuf-net" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Confluent.Kafka.Core.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
