name: build-and-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Check Docker version
      run: docker --version

    - name: Start Docker Compose
      run: docker compose -f docker-compose.yml up -d

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
      
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Wait for services availability
      run: sleep 10s
      shell: bash

    - name: Check containers
      run: docker ps -a

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal --logger GitHubActions

    - name: Stop Docker Compose
      run: docker compose -f docker-compose.yml down
